#!/usr/bin/env python3

import os.path
import sys
import re

scriptpath = os.path.dirname(sys.argv[0])
project_home = os.path.abspath(scriptpath)

musl_specs_file = "lib/musl-gcc.specs"

musl_specs = os.path.abspath(os.path.join(scriptpath, musl_specs_file))

print("musl dir  : {}".format(project_home))
print("musl specs: {}".format(musl_specs))

new_lines = ""
with open(musl_specs, "r") as reader:
    for line in reader.readlines():
        new_lines += re.sub("/usr/local/musl", project_home, line)

new_spec_file = open(musl_specs, "w+")
new_spec_file.writelines(new_lines)
new_spec_file.close()

print("Setup successfully!")
